name: Build & Deploy Keycloak Environment

on:
  workflow_dispatch:
    inputs:
      version_keycloak:
        description: Please Check Redhat base image to match the image version.
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG_VERSION: my-ecr-repo/quay.io/keycloak/keycloak:${{ github.event.inputs.version_keycloak }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          docker build . \
          --tag ${{env.DOCKER_TAG_VERSION}}
          echo "Docker image created: ${{env.DOCKER_TAG_VERSION}}" >> $GITHUB_STEP_SUMMARY
          echo "image=${{env.DOCKER_TAG_VERSION}}" >> $GITHUB_OUTPUT
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker Publish ECR ⬆️
        run: docker push ${{env.DOCKER_TAG_VERSION}}
