name: Build & Deploy Keycloak Environment

on:
  workflow_dispatch:
    inputs:
      version_keycloak:
        description: Please Check Redhat base image to match the image version.
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        id: aws_credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Setup Open Tofu
        uses: opentofu/setup-opentofu@v1
      - name: Provision ECR Repository
        working-directory: "./keycloak"
        run: |
          tofu init --backend-config="bucket=${{vars.AWS_TERRAFORM_STATE_BUCKET_NAME}}" --backend-config="key=${{vars.AWS_TERRAFORM_STATE_KEY}}.tfstate"
          tofu apply -target=module.ecr -auto-approve
        env:
          TF_VAR_access_key: "${{secrets.AWS_ACCESS_KEY_ID}}"
          TF_VAR_secret_key: "${{secrets.AWS_SECRET_ACCESS_KEY}}"
          TF_VAR_keycloak_admin_password: "${{vars.KEYCLOAK_ADMIN_PASSWORD}}"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build Docker Image
        id: docker-build
        env:
          DOCKER_TAG_VERSION: ${{steps.login-ecr.outputs.registry}}/keycloak:${{github.event.inputs.version_keycloak}}
        run: |
          docker build ./keycloak/modules/ecr/container \
          --tag ${{env.DOCKER_TAG_VERSION}}
          echo "Docker image created: ${{env.DOCKER_TAG_VERSION}}" >> $GITHUB_STEP_SUMMARY
          echo "image=${{env.DOCKER_TAG_VERSION}}" >> $GITHUB_OUTPUT
      - name: Docker Publish ECR
        run: docker push ${{steps.docker-build.outputs.image}}
      - name: Provision Keycloak Infrastructure
        working-directory: "./keycloak"
        run: |
          tofu init --backend-config="bucket=${{vars.AWS_TERRAFORM_STATE_BUCKET_NAME}}" --backend-config="key=${{vars.AWS_TERRAFORM_STATE_KEY}}.tfstate"
          tofu apply -auto-approve
        env:
          TF_VAR_access_key: "${{secrets.AWS_ACCESS_KEY_ID}}"
          TF_VAR_secret_key: "${{secrets.AWS_SECRET_ACCESS_KEY}}"
          TF_VAR_keycloak_admin_password: "${{vars.KEYCLOAK_ADMIN_PASSWORD}}"
